### ISSUE TITLE
feat: sql file upload page

### ISSUE THREAD

**Issue by HiGeuni** [sw-maestro-kumofactory/kumofactory-front#20]
### 목적

RDS에서 데이터베이스 설정을 하기 위해서는 직접 콘솔에 접근해서 DDL을 사용해야 한다.
하지만, 다수의 프로젝트를 관리해야 하는 프로젝트 특성상 보안적으로 좋지 않으므로, .sql 파일을 받아서 설정을 하려고 한다.

###  TODO
- [x] UI
- [x] File Drag & Drop
- [x] File 형식 검사
- [x] File upload from file explorer
